# Generated by Django 5.0.7 on 2024-11-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата записи")),
                ("time", models.TimeField(verbose_name="Время записи")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Сообщение"),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ФИО врача")),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Возраст"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(max_length=255, verbose_name="Специальность"),
                ),
                (
                    "qualification",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Категория"
                    ),
                ),
                (
                    "experience",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Стаж"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="medical/doctors"
                    ),
                ),
                (
                    "education",
                    models.TextField(blank=True, null=True, verbose_name="Образование"),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Дополинительные сведения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Врач",
                "verbose_name_plural": "Врачи",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата исследования"
                    ),
                ),
                (
                    "test",
                    models.CharField(
                        max_length=200, verbose_name="Название исследования"
                    ),
                ),
                ("result", models.CharField(max_length=150, verbose_name="Результат")),
                (
                    "units_of_measurement",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Единицы измерения",
                    ),
                ),
                (
                    "reference_values",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Референсные значения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат",
                "verbose_name_plural": "Результаты",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(max_length=255, verbose_name="Название услуги"),
                ),
                ("price", models.PositiveIntegerField(verbose_name="Цена")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание услуги"
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "ordering": ["service_name"],
            },
        ),
        migrations.CreateModel(
            name="Static",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.TextField(verbose_name="О компании")),
                (
                    "about",
                    models.TextField(blank=True, null=True, verbose_name="О нас"),
                ),
                (
                    "history",
                    models.TextField(blank=True, null=True, verbose_name="История"),
                ),
                (
                    "values",
                    models.TextField(blank=True, null=True, verbose_name="Ценности"),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, max_length=255, null=True, verbose_name="Адрес"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "map",
                    models.ImageField(blank=True, null=True, upload_to="medical/maps"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
            ],
            options={
                "verbose_name": "Статика",
                "verbose_name_plural": "Статика",
            },
        ),
    ]
